"""Renders the USER MODEL block for the system prompt.

Sync renderer takes a facts dict; async wrapper loads facts + living_profile.

The situation brief stored in `users.living_profile["situation_brief"]` is
generated by `temporal_brief.py` as a dict of pre-joined evidence strings
of the form:

    "{YYYY-MM-DD HH:MM} {kind}[/{role}]: {text}"

The renderer here:
  - drops `kind=chat` lines entirely (user and assistant messages are not
    facts about the user; they live in RECENT CHAT separately)
  - strips the timestamp prefix and developer-shaped type labels
  - dedupes text across sections (current_status and open_loops overlap)
  - suppresses the auto-generated meta summary
  - renders each section as a short bulleted list, not a semicolon join
"""
from __future__ import annotations

import re

from backend.memory.user_facts.schema import Confidence, FactKey, Source

_ORDER = [
    FactKey.PREFERRED_NAME,
    FactKey.HOME_CITY,
    FactKey.CURRENT_CITY,
    FactKey.HOME_TIMEZONE,
    FactKey.CURRENT_TIMEZONE,
    FactKey.PROFESSION,
    FactKey.LIFE_STAGE,
    FactKey.AGE_GROUP,
    FactKey.HOUSEHOLD,
    FactKey.PRIMARY_LANGUAGE,
    FactKey.WAKE_TIME,
    FactKey.SLEEP_TIME,
]

_LABELS = {
    FactKey.PREFERRED_NAME: "name",
    FactKey.HOME_CITY: "home city",
    FactKey.CURRENT_CITY: "current city",
    FactKey.HOME_TIMEZONE: "home timezone",
    FactKey.CURRENT_TIMEZONE: "current timezone",
    FactKey.PROFESSION: "profession",
    FactKey.LIFE_STAGE: "life stage",
    FactKey.AGE_GROUP: "age group",
    FactKey.HOUSEHOLD: "household",
    FactKey.PRIMARY_LANGUAGE: "primary language",
    FactKey.WAKE_TIME: "wake time",
    FactKey.SLEEP_TIME: "sleep time",
}

# Evidence-line parser — matches what temporal_brief.py::_format_item produces.
# Time portion is optional to accommodate pre-serialized evidence that omits
# it. Non-greedy kind capture lets "observation:expense" stay intact because
# the boundary looks for ": " (colon-space), not bare ":" — so the two-colon
# case still splits correctly.
# Matches:
#   2026-04-24 13:49 schedule: scheduled Donna message
#   2026-04-24 18:13 observation:expense: spent $6 on coffee
#   2026-04-24 17:46 chat/user: ur genuinely useless ngl
#   2026-04-22 open_loop: finish memory layer  (no time)
_EVIDENCE_RE = re.compile(
    r"^(\d{4}-\d{2}-\d{2}(?:\s+\d{1,2}:\d{2})?)\s+(\S+?):\s+(.+)$"
)

# Summaries that are developer/system metadata, not user context.
_BOILERPLATE_SUMMARY_MARKERS = (
    "timestamped postgres",
    "evidence grouped",
    "compiled state",
    "ranks unresolved",
    "suitable for saving",
    "stable facts:",
)

# Section order + human-readable label.
_SECTIONS = (
    ("current_status", "right now"),
    ("last_week", "last week"),
    ("this_week", "this week"),
    ("next_week", "coming up"),
    ("open_loops", "open threads"),
    ("stale_or_uncertain", "stale"),
)

_PER_SECTION_CAP = 4


def _is_informative(key: FactKey, fact: dict) -> bool:
    if (
        fact.get("source") == Source.DEFAULT.value
        and fact.get("confidence") == Confidence.MEDIUM.value
    ):
        return False
    return True


def render_user_model_block(facts: dict) -> str:
    if not facts:
        return ""
    present = [(k, facts[k.value]) for k in _ORDER if k.value in facts]
    has_signal = any(_is_informative(k, f) for k, f in present)
    if not has_signal:
        return ""
    lines = [f"  {_LABELS[k]}: {f.get('value', '')}" for k, f in present]
    return "USER MODEL\n" + "\n".join(lines)


def _parse_evidence_line(line: str) -> dict | None:
    m = _EVIDENCE_RE.match(line.strip())
    if not m:
        return None
    _, kind_full, text = m.groups()
    kind = kind_full
    role: str | None = None
    if "/" in kind_full and not kind_full.startswith("observation:"):
        kind, role = kind_full.split("/", 1)
    return {"kind": kind, "role": role, "text": text.strip()}


def _format_evidence(parsed: dict) -> str:
    """Strip developer prefixes; keep human-readable content."""
    kind = parsed["kind"]
    text = parsed["text"]
    if kind.startswith("observation:"):
        obs_type = kind.split(":", 1)[1]
        # If the text already names the type (e.g. "expense: spent $6"), skip
        # re-annotation. Otherwise append the type as a parenthetical.
        if obs_type and obs_type.lower() not in text.lower():
            return f"{text} ({obs_type})"
        return text
    if kind == "schedule":
        return text
    if kind == "open_loop":
        return text
    if kind == "calendar":
        return text
    return text


def _clean_section(values: list, seen: set[str]) -> list[str]:
    """Parse each evidence line, drop chat, strip prefixes, dedupe.

    `seen` is shared across sections so the same item doesn't appear in
    both current_status and open_loops (they overlap by design).
    """
    out: list[str] = []
    for raw in values:
        if not isinstance(raw, str):
            continue
        parsed = _parse_evidence_line(raw)
        if parsed is None:
            # Not a parsed evidence row — pass through verbatim.
            clean = raw.strip()
        else:
            # Drop chat lines: not facts about the user. They live in the
            # RECENT CHAT block separately and don't need to leak into the
            # situation brief as "current status".
            if parsed["kind"] == "chat":
                continue
            clean = _format_evidence(parsed)
        norm = clean.lower()
        if not clean or norm in seen:
            continue
        seen.add(norm)
        out.append(clean)
    return out


def _summary_is_boilerplate(summary: str) -> bool:
    low = summary.lower()
    return any(marker in low for marker in _BOILERPLATE_SUMMARY_MARKERS)


def render_living_profile_block(profile: dict | None) -> str:
    if not profile:
        return ""
    lines: list[str] = []
    situation = profile.get("situation_brief")
    if isinstance(situation, dict):
        header_written = False
        summary = str(situation.get("summary") or "").strip()
        if summary and not _summary_is_boilerplate(summary):
            lines.append("SITUATION BRIEF")
            header_written = True
            lines.append(f"  summary: {summary}")

        seen: set[str] = set()
        rendered_sections: list[tuple[str, list[str]]] = []
        for key, label in _SECTIONS:
            values = situation.get(key)
            if not isinstance(values, list) or not values:
                continue
            cleaned = _clean_section(values, seen)[:_PER_SECTION_CAP]
            if cleaned:
                rendered_sections.append((label, cleaned))

        if rendered_sections and not header_written:
            lines.append("SITUATION BRIEF")
            header_written = True

        for label, items in rendered_sections:
            lines.append(f"  {label}:")
            for item in items:
                lines.append(f"    - {item}")

    summary = profile.get("summary") or profile.get("narrative") or ""
    summary_str = str(summary).strip()
    if summary_str and not _summary_is_boilerplate(summary_str):
        if not lines:
            lines.extend(["LIVING PROFILE", summary_str])
        elif summary_str not in "\n".join(lines):
            lines.extend(["", "LIVING PROFILE", summary_str])

    bio = profile.get("biography") if isinstance(profile, dict) else None
    if isinstance(bio, dict):
        bio_lines: list[str] = ["BIOGRAPHY"]
        overview = (bio.get("overview") or "").strip()
        if overview:
            bio_lines.append(f"  {overview}")
        work = bio.get("work") or {}
        if isinstance(work, dict) and (work.get("employer") or work.get("role")):
            who = " ".join(
                p for p in (work.get("role"), work.get("employer")) if p
            )
            bio_lines.append(f"  work: {who}")
        rels = bio.get("relationships") or []
        for rel in rels[:5]:
            if not isinstance(rel, dict):
                continue
            name = rel.get("name") or "?"
            kind = rel.get("kind") or ""
            freq = rel.get("frequency") or ""
            tail = " · ".join(p for p in (kind, freq) if p)
            bio_lines.append(
                f"  - {name}" + (f" ({tail})" if tail else "")
            )
        interests = bio.get("interests") or []
        if interests:
            bio_lines.append(
                "  interests: " + ", ".join(str(i) for i in interests[:5])
            )
        if len(bio_lines) > 1:
            if lines:
                lines.extend(["", *bio_lines])
            else:
                lines.extend(bio_lines)

    return "\n".join(lines).strip()


async def load_and_render(user_id: str) -> str:
    """Load facts + living_profile from DB and render; empty string if nothing."""
    from backend.memory.user_facts.api import get_living_profile, get_user_facts

    facts = await get_user_facts(user_id)
    block = render_user_model_block(facts)
    profile = await get_living_profile(user_id)
    profile_block = render_living_profile_block(profile)
    if profile_block:
        block = (block + "\n\n" + profile_block).strip()
    return block
