"""Renders the USER MODEL block for the system prompt.

Sync renderer takes a facts dict; async wrapper loads facts + living_profile.

The situation brief stored in `users.living_profile["situation_brief"]` is
generated by `temporal_brief.py` as a dict of pre-joined evidence strings
of the form:

    "{YYYY-MM-DD HH:MM} {kind}[/{role}]: {text}"

The renderer here:
  - drops `kind=chat` lines entirely (user and assistant messages are not
    facts about the user; they live in RECENT CHAT separately)
  - strips the timestamp prefix and developer-shaped type labels
  - dedupes text across sections (current_status and open_loops overlap)
  - suppresses the auto-generated meta summary
  - renders each section as a short bulleted list, not a semicolon join
"""
from __future__ import annotations

import re

from backend.memory.user_facts.schema import Confidence, FactKey, Source

_ORDER = [
    # Identity card — these are what Donna reads first to know who she's
    # talking to. Order is "who am I" → "where am I" → "what do I do" →
    # "what surrounds me" → "where am I going" → "how do I run".
    FactKey.PREFERRED_NAME,
    FactKey.HOME_CITY,
    FactKey.CURRENT_CITY,
    FactKey.HOME_TIMEZONE,
    FactKey.CURRENT_TIMEZONE,
    FactKey.LIFE_STAGE,
    FactKey.AGE_GROUP,
    FactKey.EDUCATION_INSTITUTION,
    FactKey.EMPLOYER,
    FactKey.PROFESSION,
    FactKey.EXPERTISE,
    FactKey.HOUSEHOLD,
    FactKey.KEY_RELATIONSHIPS,
    FactKey.CURRENT_GOALS,
    FactKey.VALUES,
    FactKey.HOBBIES,
    FactKey.PRIMARY_LANGUAGE,
    FactKey.WAKE_TIME,
    FactKey.SLEEP_TIME,
]

_LABELS = {
    FactKey.PREFERRED_NAME: "name",
    FactKey.HOME_CITY: "home city",
    FactKey.CURRENT_CITY: "current city",
    FactKey.HOME_TIMEZONE: "home timezone",
    FactKey.CURRENT_TIMEZONE: "current timezone",
    FactKey.LIFE_STAGE: "life stage",
    FactKey.AGE_GROUP: "age group",
    FactKey.EDUCATION_INSTITUTION: "school",
    FactKey.EMPLOYER: "employer",
    FactKey.PROFESSION: "profession",
    FactKey.EXPERTISE: "expertise",
    FactKey.HOUSEHOLD: "household",
    FactKey.KEY_RELATIONSHIPS: "key relationships",
    FactKey.CURRENT_GOALS: "current goals",
    FactKey.VALUES: "values",
    FactKey.HOBBIES: "hobbies",
    FactKey.PRIMARY_LANGUAGE: "primary language",
    FactKey.WAKE_TIME: "wake time",
    FactKey.SLEEP_TIME: "sleep time",
}

# Evidence-line parser — matches what temporal_brief.py::_format_item produces.
# Time portion is optional to accommodate pre-serialized evidence that omits
# it. Non-greedy kind capture lets "observation:expense" stay intact because
# the boundary looks for ": " (colon-space), not bare ":" — so the two-colon
# case still splits correctly.
# Matches:
#   2026-04-24 13:49 schedule: scheduled Donna message
#   2026-04-24 18:13 observation:expense: spent $6 on coffee
#   2026-04-24 17:46 chat/user: ur genuinely useless ngl
#   2026-04-22 open_loop: finish memory layer  (no time)
_EVIDENCE_RE = re.compile(
    r"^(\d{4}-\d{2}-\d{2}(?:\s+\d{1,2}:\d{2})?)\s+(\S+?):\s+(.+)$"
)

# Summaries that are developer/system metadata, not user context.
_BOILERPLATE_SUMMARY_MARKERS = (
    "timestamped postgres",
    "evidence grouped",
    "compiled state",
    "ranks unresolved",
    "suitable for saving",
    "stable facts:",
)

# Section order + human-readable label.
_SECTIONS = (
    ("current_status", "right now"),
    ("last_week", "last week"),
    ("this_week", "this week"),
    ("next_week", "coming up"),
    ("open_loops", "open threads"),
    ("stale_or_uncertain", "stale"),
)

_PER_SECTION_CAP = 4

# v2 living-profile rendering. Narrative-first: the synthesizer's
# `narrative` field is the alive read Donna sees at turn time. The
# structured fields (active_tensions, watch_for_tomorrow, what_changed,
# misses, anomalies) are sidecars for downstream code (pattern miners,
# proactive triggers) and are intentionally NOT rendered as bullets —
# they would feel like a database to the model and dilute the narrative.
# Only narrative + a small set of orienting one-liners (people roster,
# rhythm) reach the system prompt.
_V2_NARRATIVE_CAP = 1200
_V2_PEOPLE_CAP = 4
_V2_THEMES_CAP = 3
_V2_THEME_CHARS_CAP = 60
_V2_TENSIONS_CAP = 3
_V2_TENSION_CHARS_CAP = 60
_V2_KEYS = (
    "narrative",
    "running_themes",
    "current_situation",
    "today_shape",
    "yesterday",
    "rhythm",
    "watch_for_tomorrow",
    "active_tensions",
    "key_people",
    "what_changed_this_week",
)


def _v2_present(profile: dict) -> bool:
    """True when the profile carries any v2 synthesizer field with content."""
    for key in _V2_KEYS:
        value = profile.get(key)
        if value in (None, "", [], {}):
            continue
        return True
    return False


def _trim(text: str, limit: int) -> str:
    """Truncate text to <= limit chars at a sentence or word boundary.

    Mid-word truncation with `...` makes the rendered LP read like a
    redacted document — Donna sees `(4-6am cluster...` and tries to
    parse half a thought. This trim looks for a sentence boundary
    (`. `, `? `, `! `, or newline equivalents) in the back ~40% of the
    window; falls back to the last word boundary; only as a final
    resort does it hard-cap and append `...`. The caller sets `limit`
    high enough that this latter case is rare in practice.
    """
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    head = text[:limit]
    soft_floor = int(limit * 0.6)
    # Try sentence boundary first — keeps the rendered field readable.
    for boundary in (". ", "? ", "! ", ".\n", "?\n", "!\n"):
        idx = head.rfind(boundary, soft_floor)
        if idx > 0:
            return text[: idx + 1].rstrip()
    # No sentence boundary in window — fall back to word boundary.
    space_idx = head.rfind(" ", soft_floor)
    if space_idx > 0:
        return text[:space_idx].rstrip()
    # Worst case: text is one giant token. Hard-cap with marker.
    return text[: max(0, limit - 3)].rstrip() + "..."


def _render_v2_living_profile(profile: dict) -> list[str]:
    lines: list[str] = ["LIVING PROFILE"]

    # Narrative leads. If the synth produced one, it carries the work.
    # Fall back to current_situation only when narrative is missing
    # (older profiles persisted before the schema changed).
    narrative = _trim(str(profile.get("narrative") or ""), _V2_NARRATIVE_CAP)
    if not narrative:
        narrative = _trim(
            str(profile.get("current_situation") or ""), _V2_NARRATIVE_CAP
        )
    if narrative:
        lines.append(narrative)

    # Running themes — ambient frame for the longer arc (last 14-30 days).
    # One comma-joined line so Donna can read the durations without
    # parsing the narrative for them.
    themes = profile.get("running_themes") or []
    if isinstance(themes, list):
        cleaned_themes: list[str] = []
        for theme in themes[:_V2_THEMES_CAP]:
            phrase = str(theme).strip()
            if not phrase:
                continue
            cleaned_themes.append(_trim(phrase, _V2_THEME_CHARS_CAP))
        if cleaned_themes:
            lines.append("themes: " + "; ".join(cleaned_themes))

    # Compact people roster — names and current dynamic, comma-joined.
    # Useful for the model to know who's actively in this user's life
    # this week without forcing the narrative to enumerate everyone.
    people = profile.get("key_people") or []
    if isinstance(people, list):
        rendered_people: list[str] = []
        for person in people[:_V2_PEOPLE_CAP]:
            if not isinstance(person, dict):
                continue
            name = (person.get("name") or "").strip()
            if not name:
                continue
            role = (person.get("role") or "").strip()
            dynamic = (person.get("current_dynamic") or "").strip()
            tail_parts = [part for part in (role, dynamic) if part]
            tail = ", ".join(tail_parts)
            rendered_people.append(
                f"{name} ({tail})" if tail else name
            )
        if rendered_people:
            lines.append("people: " + "; ".join(rendered_people))

    # One-line rhythm so the model can read time-of-day signal without
    # parsing the narrative. Cheap to render, costly when missing.
    rhythm = profile.get("rhythm") or {}
    if isinstance(rhythm, dict):
        wake = (rhythm.get("typical_wake_window") or "").strip()
        engage = (rhythm.get("typical_first_engage_window") or "").strip()
        rhythm_parts: list[str] = []
        if wake:
            rhythm_parts.append(f"up {wake}")
        if engage:
            rhythm_parts.append(f"first engages {engage}")
        median = rhythm.get("typical_message_gap_median_hours")
        if isinstance(median, (int, float)) and median > 0:
            rhythm_parts.append(f"avg gap ~{median:.1f}h")
        if rhythm_parts:
            lines.append("rhythm: " + ", ".join(rhythm_parts))

    # Emotional read + active tensions — a single ambient signal the
    # model uses to calibrate voice (calm vs stressed vs hopeful) and
    # to know what's pulling on the user without re-parsing the
    # narrative. Auto-rendering THESE as instructions would push us
    # back toward procedural rules; rendering as a short status line
    # keeps it ambient.
    temperature = (profile.get("emotional_temperature") or "").strip().lower()
    tensions = profile.get("active_tensions") or []
    cleaned_tensions: list[str] = []
    if isinstance(tensions, list):
        for t in tensions[:_V2_TENSIONS_CAP]:
            phrase = str(t).strip()
            if not phrase:
                continue
            cleaned_tensions.append(_trim(phrase, _V2_TENSION_CHARS_CAP))
    if temperature or cleaned_tensions:
        bits: list[str] = []
        if temperature:
            bits.append(temperature)
        if cleaned_tensions:
            bits.append("(" + ", ".join(cleaned_tensions) + ")")
        lines.append("read: " + " ".join(bits))

    # today_shape and watch_for_tomorrow are intentionally NOT rendered.
    # Both can carry absolute-time framing ("today's deploy at 6pm",
    # "tomorrow's flight") that goes stale by the next day. Donna reads
    # the LP at unknown future times, so any "today/tomorrow" claim is a
    # time-bomb. The TODAY block (live DB read each turn) carries actual
    # current state; the LP narrative carries the slow ambient knowing
    # of who the user is this week. Both fields stay in the structured
    # profile for downstream pattern miners and proactive triggers.

    return lines if len(lines) > 1 else []


def _is_informative(key: FactKey, fact: dict) -> bool:
    if (
        fact.get("source") == Source.DEFAULT.value
        and fact.get("confidence") == Confidence.MEDIUM.value
    ):
        return False
    return True


def render_user_model_block(facts: dict) -> str:
    if not facts:
        return ""
    present = [(k, facts[k.value]) for k in _ORDER if k.value in facts]
    has_signal = any(_is_informative(k, f) for k, f in present)
    if not has_signal:
        return ""
    lines = [f"  {_LABELS[k]}: {f.get('value', '')}" for k, f in present]
    return "USER MODEL\n" + "\n".join(lines)


def _parse_evidence_line(line: str) -> dict | None:
    m = _EVIDENCE_RE.match(line.strip())
    if not m:
        return None
    _, kind_full, text = m.groups()
    kind = kind_full
    role: str | None = None
    if "/" in kind_full and not kind_full.startswith("observation:"):
        kind, role = kind_full.split("/", 1)
    return {"kind": kind, "role": role, "text": text.strip()}


def _format_evidence(parsed: dict) -> str:
    """Strip developer prefixes; keep human-readable content."""
    kind = parsed["kind"]
    text = parsed["text"]
    if kind.startswith("observation:"):
        obs_type = kind.split(":", 1)[1]
        # If the text already names the type (e.g. "expense: spent $6"), skip
        # re-annotation. Otherwise append the type as a parenthetical.
        if obs_type and obs_type.lower() not in text.lower():
            return f"{text} ({obs_type})"
        return text
    if kind == "schedule":
        return text
    if kind == "open_loop":
        return text
    if kind == "calendar":
        return text
    return text


def _clean_section(values: list, seen: set[str]) -> list[str]:
    """Parse each evidence line, drop chat, strip prefixes, dedupe.

    `seen` is shared across sections so the same item doesn't appear in
    both current_status and open_loops (they overlap by design).
    """
    out: list[str] = []
    for raw in values:
        if not isinstance(raw, str):
            continue
        parsed = _parse_evidence_line(raw)
        if parsed is None:
            # Not a parsed evidence row — pass through verbatim.
            clean = raw.strip()
        else:
            # Drop chat lines: not facts about the user. They live in the
            # RECENT CHAT block separately and don't need to leak into the
            # situation brief as "current status".
            if parsed["kind"] == "chat":
                continue
            clean = _format_evidence(parsed)
        norm = clean.lower()
        if not clean or norm in seen:
            continue
        seen.add(norm)
        out.append(clean)
    return out


def _summary_is_boilerplate(summary: str) -> bool:
    low = summary.lower()
    return any(marker in low for marker in _BOILERPLATE_SUMMARY_MARKERS)


def render_living_profile_block(profile: dict | None) -> str:
    if not profile:
        return ""

    # v2 path — new synthesizer output. Renders the rich Living Profile and
    # short-circuits the legacy situation_brief/biography rendering. We
    # still render the legacy summary/biography blocks if a v1 profile
    # carries them (back-compat for users whose profile predates v2).
    if _v2_present(profile):
        v2_lines = _render_v2_living_profile(profile)
        if v2_lines:
            return "\n".join(v2_lines).strip()

    lines: list[str] = []
    situation = profile.get("situation_brief")
    if isinstance(situation, dict):
        header_written = False
        summary = str(situation.get("summary") or "").strip()
        if summary and not _summary_is_boilerplate(summary):
            lines.append("SITUATION BRIEF")
            header_written = True
            lines.append(f"  summary: {summary}")

        seen: set[str] = set()
        rendered_sections: list[tuple[str, list[str]]] = []
        for key, label in _SECTIONS:
            values = situation.get(key)
            if not isinstance(values, list) or not values:
                continue
            cleaned = _clean_section(values, seen)[:_PER_SECTION_CAP]
            if cleaned:
                rendered_sections.append((label, cleaned))

        if rendered_sections and not header_written:
            lines.append("SITUATION BRIEF")
            header_written = True

        for label, items in rendered_sections:
            lines.append(f"  {label}:")
            for item in items:
                lines.append(f"    - {item}")

    summary = profile.get("summary") or profile.get("narrative") or ""
    summary_str = str(summary).strip()
    if summary_str and not _summary_is_boilerplate(summary_str):
        if not lines:
            lines.extend(["LIVING PROFILE", summary_str])
        elif summary_str not in "\n".join(lines):
            lines.extend(["", "LIVING PROFILE", summary_str])

    bio = profile.get("biography") if isinstance(profile, dict) else None
    if isinstance(bio, dict):
        bio_lines: list[str] = ["BIOGRAPHY"]
        overview = (bio.get("overview") or "").strip()
        if overview:
            bio_lines.append(f"  {overview}")
        work = bio.get("work") or {}
        if isinstance(work, dict) and (work.get("employer") or work.get("role")):
            who = " ".join(
                p for p in (work.get("role"), work.get("employer")) if p
            )
            bio_lines.append(f"  work: {who}")
        rels = bio.get("relationships") or []
        for rel in rels[:5]:
            if not isinstance(rel, dict):
                continue
            name = rel.get("name") or "?"
            kind = rel.get("kind") or ""
            freq = rel.get("frequency") or ""
            tail = " · ".join(p for p in (kind, freq) if p)
            bio_lines.append(
                f"  - {name}" + (f" ({tail})" if tail else "")
            )
        interests = bio.get("interests") or []
        if interests:
            bio_lines.append(
                "  interests: " + ", ".join(str(i) for i in interests[:5])
            )
        if len(bio_lines) > 1:
            if lines:
                lines.extend(["", *bio_lines])
            else:
                lines.extend(bio_lines)

    return "\n".join(lines).strip()


async def load_and_render(user_id: str) -> str:
    """Load facts + living_profile from DB and render; empty string if nothing."""
    from backend.memory.user_facts.api import get_living_profile, get_user_facts

    facts = await get_user_facts(user_id)
    block = render_user_model_block(facts)
    profile = await get_living_profile(user_id)
    profile_block = render_living_profile_block(profile)
    if profile_block:
        block = (block + "\n\n" + profile_block).strip()
    return block
